# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hongx/CLionProjects/simkv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hongx/CLionProjects/simkv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hongx/CLionProjects/simkv/CMakeFiles /Users/hongx/CLionProjects/simkv//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hongx/CLionProjects/simkv/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hongx/CLionProjects/simkv/CMakeFiles /Users/hongx/CLionProjects/simkv//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hongx/CLionProjects/simkv/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simkv

# Build rule for target.
simkv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simkv
.PHONY : simkv

# fast build rule for target.
simkv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simkv.dir/build.make CMakeFiles/simkv.dir/build
.PHONY : simkv/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simkv.dir/build.make CMakeFiles/simkv.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simkv.dir/build.make CMakeFiles/simkv.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simkv.dir/build.make CMakeFiles/simkv.dir/main.cpp.s
.PHONY : main.cpp.s

parser/cnf_parser.o: parser/cnf_parser.cpp.o
.PHONY : parser/cnf_parser.o

# target to build an object file
parser/cnf_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simkv.dir/build.make CMakeFiles/simkv.dir/parser/cnf_parser.cpp.o
.PHONY : parser/cnf_parser.cpp.o

parser/cnf_parser.i: parser/cnf_parser.cpp.i
.PHONY : parser/cnf_parser.i

# target to preprocess a source file
parser/cnf_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simkv.dir/build.make CMakeFiles/simkv.dir/parser/cnf_parser.cpp.i
.PHONY : parser/cnf_parser.cpp.i

parser/cnf_parser.s: parser/cnf_parser.cpp.s
.PHONY : parser/cnf_parser.s

# target to generate assembly for a file
parser/cnf_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simkv.dir/build.make CMakeFiles/simkv.dir/parser/cnf_parser.cpp.s
.PHONY : parser/cnf_parser.cpp.s

posix/server.o: posix/server.cpp.o
.PHONY : posix/server.o

# target to build an object file
posix/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simkv.dir/build.make CMakeFiles/simkv.dir/posix/server.cpp.o
.PHONY : posix/server.cpp.o

posix/server.i: posix/server.cpp.i
.PHONY : posix/server.i

# target to preprocess a source file
posix/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simkv.dir/build.make CMakeFiles/simkv.dir/posix/server.cpp.i
.PHONY : posix/server.cpp.i

posix/server.s: posix/server.cpp.s
.PHONY : posix/server.s

# target to generate assembly for a file
posix/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simkv.dir/build.make CMakeFiles/simkv.dir/posix/server.cpp.s
.PHONY : posix/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... simkv"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parser/cnf_parser.o"
	@echo "... parser/cnf_parser.i"
	@echo "... parser/cnf_parser.s"
	@echo "... posix/server.o"
	@echo "... posix/server.i"
	@echo "... posix/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

